/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TablaContactosForma1;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //llamamos al metodo despues el initComponets porque primero tiene  que inicializar los componentes
        inicializarTabla();
    }

    //hacemos este metodo para inicializar la tabla modelo
      private void inicializarTabla(){
          //creamos el modelo tabla
        DefaultTableModel dtm= new DefaultTableModel();
        
        //le asignamos las columnas con los nombres identificadores que queramos que se lo pasamos como array
        dtm.setColumnIdentifiers(new String[]{"Nombre ","Apellidos ", "telefono"} );
        
        //ahora que ya tenemos el modelo de tabla con las columnas identificadoras creadas le añadimos el modelo a nuestra tabal
        jTable_tabla.setModel(dtm);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu_Alta = new javax.swing.JMenu();
        jMenuItem1_Alta = new javax.swing.JMenuItem();
        jMenuItem_Baja = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_tabla);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jMenu_Alta.setText("Contacto");

        jMenuItem1_Alta.setText("Alta...");
        jMenuItem1_Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_AltaActionPerformed(evt);
            }
        });
        jMenu_Alta.add(jMenuItem1_Alta);

        jMenuItem_Baja.setText("Baja...");
        jMenuItem_Baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_BajaActionPerformed(evt);
            }
        });
        jMenu_Alta.add(jMenuItem_Baja);

        jMenuBar2.add(jMenu_Alta);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_AltaActionPerformed
        DialogAlta dialogAlta= new DialogAlta(this, true);
        dialogAlta.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem1_AltaActionPerformed

    private void jMenuItem_BajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_BajaActionPerformed
       
        int fila;
        //seleccionamos la fila
        fila=jTable_tabla.getSelectedRow();
        
       
        if(fila==-1){
            jLabel1.setText("selecciona una linea");
        }else {
            //sacamos el modelo para interactuar sobre el porque el jTable es solo para que se vea bien
            DefaultTableModel dtm=(DefaultTableModel)jTable_tabla.getModel();
            //usamos la variable para usar el metodo de borrar y borrar la fila seleccionada
            dtm.removeRow(fila);
        }
        
    }//GEN-LAST:event_jMenuItem_BajaActionPerformed

  
    
    public void aniadirContacto(Contacto contacto){
        //el ciliente se añade a traves del modelo y no de la tabla en si
        //como ya tenemos el modelo no creamos uno nuevo porque si no lo sobreescribiriamos
        DefaultTableModel dtm=(DefaultTableModel) jTable_tabla.getModel();
        
        //una vez extraido le añadimos la fila y tenemos que pasarle como parametro un array y como el contancto tiene un metodo que devuelve  
        //una array con su informacion, es lo que le pasamos
        dtm.addRow(contacto.ContactosArray());
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1_Alta;
    private javax.swing.JMenuItem jMenuItem_Baja;
    private javax.swing.JMenu jMenu_Alta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tabla;
    // End of variables declaration//GEN-END:variables

   

  
}
