/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JugarVentanas;

import java.awt.Dialog;

/**
 *
 * @author andre
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Abrir1 = new javax.swing.JButton();
        jButton_Abrir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Abrir1.setText("ABRIR 1");
        jButton_Abrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Abrir1ActionPerformed(evt);
            }
        });

        jButton_Abrir2.setText("ABRIR 2");
        jButton_Abrir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Abrir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton_Abrir1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jButton_Abrir2)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Abrir1)
                    .addComponent(jButton_Abrir2))
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Abrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Abrir1ActionPerformed

//creamos el dialogo o frame que queramos mostrar al darle a este boton
                                              //le ponemos siempre false porque si no seria modal todo, luego abajo especificamos lo que queramos que sea  modal o no
        Ventana1 ventana1 = new Ventana1(this, false);

        
        //para bloquear la ventana superior y no pueda acceder a ella
        ventana1.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        
            //hacemos que sea visible  y es lo ultimo para que apliquen los cambios antes de mostrarla    
        ventana1.setVisible(true);


    }//GEN-LAST:event_jButton_Abrir1ActionPerformed

    private void jButton_Abrir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Abrir2ActionPerformed
       Ventana2 ventana2= new Ventana2(this, false);
       
       
       //para permitir el acceso a la ventana superior (esto hace que cuando salga la ventana 2  podamos accedar a la 1 que es en la que estamos escribiendo esto)
       ventana2.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        ventana2.setVisible(true);
    }//GEN-LAST:event_jButton_Abrir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Abrir1;
    private javax.swing.JButton jButton_Abrir2;
    // End of variables declaration//GEN-END:variables
}
