/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JugarVentanas;

/**
 *
 * @author andre
 */
public class Ventana1 extends javax.swing.JDialog {
    
JFrame frame;
    /**
     * Creates new form JDialog
     */
    public Ventana1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        //para que construya basandose en el padre
        frame= new JFrame();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Abrir3 = new javax.swing.JButton();
        jButton_Volver = new javax.swing.JButton();
        jLabel_Ventana1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_Abrir3.setText("Abrir 3");
        jButton_Abrir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Abrir3ActionPerformed(evt);
            }
        });

        jButton_Volver.setText("Volver");
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        jLabel_Ventana1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Ventana1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_Ventana1.setText("   Ventana 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton_Abrir3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Volver)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel_Ventana1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel_Ventana1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Abrir3)
                    .addComponent(jButton_Volver))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
 
        //para cerrar la ventana 
        this.dispose();
    }//GEN-LAST:event_jButton_VolverActionPerformed

    private void jButton_Abrir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Abrir3ActionPerformed
      Ventana3 ventana3= new Ventana3(this, false);
      ventana3.setModalityType(DEFAULT_MODALITY_TYPE.TOOLKIT_MODAL);
      ventana3.setVisible(true);
      
    }//GEN-LAST:event_jButton_Abrir3ActionPerformed

    //se borra el main
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Abrir3;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JLabel jLabel_Ventana1;
    // End of variables declaration//GEN-END:variables
}
