/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TablaContactosForma2;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author andre
 */
public class TableModel extends javax.swing.JFrame {

    /**
     * Creates new form TableModel
     */
    public TableModel() {
        initComponents();
        refrescarTabla();
    }
    
    private void refrescarTabla(){
        
        //creamos el modelo de tabla
        DefaultTableModel dtm= new DefaultTableModel();
        //le añadimos las cabeceras
        dtm.setColumnIdentifiers(new String[]{"Nombre","apellido","fecha"});
        //extraigo de la lista todos los contactos para meterlos en la tabla
        List<Contacto> listaContactos=LogicaNegocio.gestListaContactos();
        //hago un forech para que recorra la lista y los vaya grabando en la tabla
        for (Contacto contacto : listaContactos) {
            
            dtm.addRow(contacto.arrayContacto());
        }
        
        
        //le asignamos el modelo a nuestra tabla
        jTable_tabla.setModel(dtm);
        
        //para ordenar 
         TableRowSorter<javax.swing.table.TableModel> elQueOrdena= new TableRowSorter<>(dtm);
        jTable_tabla.setRowSorter(elQueOrdena);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabla = new javax.swing.JTable();
        jLabel_Error = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Alta = new javax.swing.JMenu();
        jMenu_Baja = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_tabla);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jLabel_Error, java.awt.BorderLayout.PAGE_END);

        jMenu_Alta.setText("ALTA");
        jMenu_Alta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_AltaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_Alta);

        jMenu_Baja.setText("BAJA");
        jMenu_Baja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_BajaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_Baja);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_AltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_AltaMouseClicked
       //creamos la segunda ventana que va abrirse cuando pulemos en el menu alta
        JDialog_Alta alta= new JDialog_Alta(this, true);
        
        //le asiganmos que sea visible
        alta.setVisible(true);
        //este refrescar no se ejecutaa hasta el setVisible no se quite
        refrescarTabla();
    }//GEN-LAST:event_jMenu_AltaMouseClicked

    private void jMenu_BajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_BajaMouseClicked
   
        int fila = jTable_tabla.getSelectedRow();
        
        if(fila==-1){
            jLabel_Error.setText("no ha seleccionado ninguna fila");
        }else {
            
        
          DefaultTableModel dtm= (DefaultTableModel)jTable_tabla.getModel();
          dtm.removeRow(fila);
        
    }//GEN-LAST:event_jMenu_BajaMouseClicked
 }
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Error;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Alta;
    private javax.swing.JMenu jMenu_Baja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tabla;
    // End of variables declaration//GEN-END:variables
}
