/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di_evalu_1;

/**
 *
 * @author andre
 */
public class JDialog1 extends javax.swing.JDialog {
    
    //para lo que pongamos en el dialogo se nos vaya al frame
    private JFrame1 ventanaPrincipal;

    /**
     * Creates new form JDialog1
     */
    public JDialog1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        //para llamar a otra ventana de la hija al padre 
        ventanaPrincipal=(JFrame1)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Volver = new javax.swing.JButton();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel1_llamas = new javax.swing.JLabel();
        jLabel_Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_Volver.setText("Volver");
        jButton_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_VolverMouseClicked(evt);
            }
        });
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jLabel1_llamas.setText("¿Como te llamas?");

        jLabel_Error.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Error.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton_Volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1_llamas, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jLabel_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1_llamas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jButton_Volver)
                .addGap(118, 118, 118)
                .addComponent(jLabel_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jButton_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_VolverMouseClicked
        
        // esto es para ver si el texfield esta vacio con (el isEmpty)
        if(jTextField_nombre.getText().isEmpty()){
            
            jLabel_Error.setText("Introducce un nombre");
            
        }else{
            
            //es el metodo que habiammos creado en el main para asignarle un string al label, le pasamos como parameto el texto que hemos introduceo en el texfield de la segunda ventana
            ventanaPrincipal.mostrarSaludo(jTextField_nombre.getText());
            
            // ponemos visible false para que una vez le demos al boton desaparezca y muestre la otra ventana
            setVisible(false);
        }
    }//GEN-LAST:event_jButton_VolverMouseClicked

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_VolverActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JLabel jLabel1_llamas;
    private javax.swing.JLabel jLabel_Error;
    private javax.swing.JTextField jTextField_nombre;
    // End of variables declaration//GEN-END:variables
}
