/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DI_Encuesta;

import javax.swing.JDialog;

/**
 *
 * @author andre
 */
public class JFrame_Encuesta extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Encuesta
     */
    public JFrame_Encuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1_Sexo = new javax.swing.ButtonGroup();
        jPanel1_Encuesta = new javax.swing.JPanel();
        jTextField1_Profesión = new javax.swing.JTextField();
        jLabel1_Profesíon = new javax.swing.JLabel();
        jLabel2_NºHermanos = new javax.swing.JLabel();
        jSpinner1_NumeroHermanos = new javax.swing.JSpinner();
        jLabel3_Edad = new javax.swing.JLabel();
        jComboBox1_EdadHermanos = new javax.swing.JComboBox<>();
        jPanel1_Sexo = new javax.swing.JPanel();
        jRadioButton1_Mujer = new javax.swing.JRadioButton();
        jRadioButton2_Hombre = new javax.swing.JRadioButton();
        jCheckBox1_Deporte = new javax.swing.JCheckBox();
        jPanel1_elegirDeporte = new javax.swing.JPanel();
        jScrollPane1_Deportes = new javax.swing.JScrollPane();
        jList1_Deportes = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1_Marcar_Aficion = new javax.swing.JLabel();
        jLabel2_Compras = new javax.swing.JLabel();
        jSlider1_Compras = new javax.swing.JSlider();
        jLabel31_Television = new javax.swing.JLabel();
        jSlider2_television = new javax.swing.JSlider();
        jLabel1_Cine = new javax.swing.JLabel();
        jSlider1_Cine = new javax.swing.JSlider();
        jButton1_Acepatr = new javax.swing.JButton();
        jButton2_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1_Encuesta.setBackground(new java.awt.Color(153, 153, 255));

        jTextField1_Profesión.setText("jTextField1");

        jLabel1_Profesíon.setText("Profesión:");

        jLabel2_NºHermanos.setText("Nº Hermanos: ");

        jLabel3_Edad.setText("Edad: ");

        jComboBox1_EdadHermanos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menor de 18 años", "Entre 18 y 30 años", "Mayor de 30 años" }));
        jComboBox1_EdadHermanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_EdadHermanosActionPerformed(evt);
            }
        });

        jPanel1_Sexo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jPanel1_Sexo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        buttonGroup1_Sexo.add(jRadioButton1_Mujer);
        jRadioButton1_Mujer.setText("Mujer");

        buttonGroup1_Sexo.add(jRadioButton2_Hombre);
        jRadioButton2_Hombre.setText("Hombre");

        javax.swing.GroupLayout jPanel1_SexoLayout = new javax.swing.GroupLayout(jPanel1_Sexo);
        jPanel1_Sexo.setLayout(jPanel1_SexoLayout);
        jPanel1_SexoLayout.setHorizontalGroup(
            jPanel1_SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_SexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1_Mujer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jRadioButton2_Hombre, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1_SexoLayout.setVerticalGroup(
            jPanel1_SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_SexoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1_SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1_Mujer)
                    .addComponent(jRadioButton2_Hombre))
                .addGap(18, 18, 18))
        );

        jCheckBox1_Deporte.setText("¿ Práctica algún Deporte ?");
        jCheckBox1_Deporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_DeporteActionPerformed(evt);
            }
        });

        jPanel1_elegirDeporte.setBorder(javax.swing.BorderFactory.createTitledBorder("¿Cual?"));
        jPanel1_elegirDeporte.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jList1_Deportes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tenis", "Fútbol", "Boxeo", "Padel", "Gimnasio" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1_Deportes.setViewportView(jList1_Deportes);

        javax.swing.GroupLayout jPanel1_elegirDeporteLayout = new javax.swing.GroupLayout(jPanel1_elegirDeporte);
        jPanel1_elegirDeporte.setLayout(jPanel1_elegirDeporteLayout);
        jPanel1_elegirDeporteLayout.setHorizontalGroup(
            jPanel1_elegirDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_elegirDeporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1_Deportes, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1_elegirDeporteLayout.setVerticalGroup(
            jPanel1_elegirDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_elegirDeporteLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1_Deportes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1_Marcar_Aficion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1_Marcar_Aficion.setText("Marque del 1 al 10 su grado de afición en: ");

        jLabel2_Compras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2_Compras.setText("Compras: ");

        jSlider1_Compras.setMajorTickSpacing(10);
        jSlider1_Compras.setMaximum(10);
        jSlider1_Compras.setMinorTickSpacing(1);
        jSlider1_Compras.setPaintLabels(true);
        jSlider1_Compras.setToolTipText("");
        jSlider1_Compras.setValue(5);
        jSlider1_Compras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel31_Television.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31_Television.setText("Ver Televisión: ");

        jSlider2_television.setMajorTickSpacing(10);
        jSlider2_television.setMaximum(10);
        jSlider2_television.setMinorTickSpacing(1);
        jSlider2_television.setPaintLabels(true);
        jSlider2_television.setValue(5);

        jLabel1_Cine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1_Cine.setText("Ir al cine: ");

        jSlider1_Cine.setMajorTickSpacing(10);
        jSlider1_Cine.setMaximum(10);
        jSlider1_Cine.setMinorTickSpacing(1);
        jSlider1_Cine.setPaintLabels(true);
        jSlider1_Cine.setValue(5);

        jButton1_Acepatr.setText("Aceptar");
        jButton1_Acepatr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_AcepatrActionPerformed(evt);
            }
        });

        jButton2_Cancelar.setText("Cancelar");
        jButton2_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_EncuestaLayout = new javax.swing.GroupLayout(jPanel1_Encuesta);
        jPanel1_Encuesta.setLayout(jPanel1_EncuestaLayout);
        jPanel1_EncuestaLayout.setHorizontalGroup(
            jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                        .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jPanel1_elegirDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                                        .addComponent(jLabel2_NºHermanos)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinner1_NumeroHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3_Edad))
                                    .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                                        .addComponent(jLabel1_Profesíon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1_Profesión, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1_EdadHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jPanel1_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_EncuestaLayout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_Marcar_Aficion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_Compras)))
                    .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider2_television, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_EncuestaLayout.createSequentialGroup()
                                .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                                        .addComponent(jSlider1_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1_Acepatr))
                                    .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel31_Television)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(91, 91, 91)))))
                .addContainerGap())
            .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBox1_Deporte, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1_Cine)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSlider1_Cine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_EncuestaLayout.setVerticalGroup(
            jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_EncuestaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Profesión, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_Profesíon))
                .addGap(32, 32, 32)
                .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_NºHermanos)
                    .addComponent(jSpinner1_NumeroHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3_Edad)
                    .addComponent(jComboBox1_EdadHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jPanel1_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox1_Deporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1_elegirDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1_Marcar_Aficion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2_Compras)
                .addGap(18, 18, 18)
                .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_Acepatr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1_EncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31_Television)
                    .addComponent(jButton2_Cancelar))
                .addGap(21, 21, 21)
                .addComponent(jSlider2_television, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_Cine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1_Cine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1_Encuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1_Encuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_EdadHermanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_EdadHermanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_EdadHermanosActionPerformed

    private void jCheckBox1_DeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_DeporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1_DeporteActionPerformed

    private void jButton2_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_CancelarActionPerformed

    private void jButton1_AcepatrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_AcepatrActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_AcepatrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1_Sexo;
    private javax.swing.JButton jButton1_Acepatr;
    private javax.swing.JButton jButton2_Cancelar;
    private javax.swing.JCheckBox jCheckBox1_Deporte;
    private javax.swing.JComboBox<String> jComboBox1_EdadHermanos;
    private javax.swing.JLabel jLabel1_Cine;
    private javax.swing.JLabel jLabel1_Marcar_Aficion;
    private javax.swing.JLabel jLabel1_Profesíon;
    private javax.swing.JLabel jLabel2_Compras;
    private javax.swing.JLabel jLabel2_NºHermanos;
    private javax.swing.JLabel jLabel31_Television;
    private javax.swing.JLabel jLabel3_Edad;
    private javax.swing.JList<String> jList1_Deportes;
    private javax.swing.JPanel jPanel1_Encuesta;
    private javax.swing.JPanel jPanel1_Sexo;
    private javax.swing.JPanel jPanel1_elegirDeporte;
    private javax.swing.JRadioButton jRadioButton1_Mujer;
    private javax.swing.JRadioButton jRadioButton2_Hombre;
    private javax.swing.JScrollPane jScrollPane1_Deportes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1_Cine;
    private javax.swing.JSlider jSlider1_Compras;
    private javax.swing.JSlider jSlider2_television;
    private javax.swing.JSpinner jSpinner1_NumeroHermanos;
    private javax.swing.JTextField jTextField1_Profesión;
    // End of variables declaration//GEN-END:variables
}
